name: Release PyPI wheel Jobs

on:
  push:
    tags:
      - 'v*'

jobs:
  macOS:
    name: Wheel Build
    runs-on: centos-latest
    steps:
      - name: Check source code
        uses: actions/checkout@master
        with:
          ref: master

      - name: Build environment
        shell: bash
        run: |
          python -m pip install --upgrade pip
          pip install setuptools wheel twine
          python setup.py sdist bdist_wheel
          twine upload dist/*.whl